import { DishCategory, RestaurantTag } from '@/shared/enums';
import { Cuisine, MenuData, Restaurant, Review } from '@/shared/types';

export const allRestaurants: Restaurant[] = [
	{
		id: '1',
		name: 'Sant Francesc Restaurant',
		minimumPrice: 15,
		cuisineId: '1', // Mediterranean
		rating: 4.5,
		mainImage:
			'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
		profileImage:
			'https://visitbegur.cat/wp-content/uploads/2021/06/mooma-1024x813.jpg',
		images: [
			'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
			'https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg',
			'https://images.pexels.com/photos/1907228/pexels-photo-1907228.jpeg',
		],
		distance: 2.5,
		address: {
			street: 'Carrer Rector Ubach',
			number: '50',
			additionalInformation: '2º A',
			postalCode: '08006',
			city: 'Barcelona',
			country: 'España',
			coordinates: {
				latitude: 41.3951,
				longitude: 2.1834,
			},
			formattedAddress:
				'Carrer Rector Ubach, 50, 2º A, 08006 Barcelona, España',
		},
		tags: [
			RestaurantTag.AIR_CONDITIONING,
			RestaurantTag.VEGETARIAN,
			RestaurantTag.FAMILY_FRIENDLY,
		],
		menus: [],
		phone: '+34 123 456 789',
		reservationLink: 'https://reservas.santfrancesc.com',
	},
	{
		id: '2',
		name: 'Tika Tacos',
		minimumPrice: 12,
		cuisineId: '4', // Mexican
		rating: 4.0,
		mainImage:
			'https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg',
		profileImage:
			'https://visitbegur.cat/wp-content/uploads/2021/06/mooma-1024x813.jpg',
		images: [
			'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
			'https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg',
			'https://images.pexels.com/photos/1907228/pexels-photo-1907228.jpeg',
		],
		distance: 3.0,
		address: {
			street: 'Carrer de la Pau',
			number: '25',
			additionalInformation: 'Local 3',
			postalCode: '08001',
			city: 'Barcelona',
			country: 'España',
			coordinates: {
				latitude: 41.4051,
				longitude: 2.1934,
			},
			formattedAddress:
				'Carrer de la Pau, 25, Local 3, 08001 Barcelona, España',
		},
		tags: [
			RestaurantTag.AIR_CONDITIONING,
			RestaurantTag.GLUTEN_FREE,
			RestaurantTag.LIVE_MUSIC,
		],
		menus: [],
		phone: '+34 987 654 321',
	},
	{
		id: '3',
		name: 'El gran sol',
		minimumPrice: 10,
		cuisineId: '6', // Chinese
		rating: 4.8,
		mainImage:
			'https://images.pexels.com/photos/1907228/pexels-photo-1907228.jpeg',
		profileImage:
			'https://visitbegur.cat/wp-content/uploads/2021/06/mooma-1024x813.jpg',
		images: [
			'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
			'https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg',
			'https://images.pexels.com/photos/1907228/pexels-photo-1907228.jpeg',
		],
		distance: 1.5,
		address: {
			street: 'Avinguda Diagonal',
			number: '123',
			additionalInformation: 'Baix B',
			postalCode: '08028',
			city: 'Barcelona',
			country: 'España',
			coordinates: {
				latitude: 41.3851,
				longitude: 2.1734,
			},
			formattedAddress:
				'Avinguda Diagonal, 123, Baix B, 08028 Barcelona, España',
		},
		tags: [
			RestaurantTag.AIR_CONDITIONING,
			RestaurantTag.RESERVATIONS,
			RestaurantTag.PET_FRIENDLY,
		],
		menus: [],
		reservationLink: 'https://elgransol.opentable.com',
	},
	{
		id: '4',
		name: 'Sakura Tokyo',
		minimumPrice: 18,
		cuisineId: '2', // Japanese
		rating: 4.7,
		mainImage:
			'https://images.pexels.com/photos/2098085/pexels-photo-2098085.jpeg',
		profileImage:
			'https://images.pexels.com/photos/2098085/pexels-photo-2098085.jpeg',
		images: [
			'https://images.pexels.com/photos/2098085/pexels-photo-2098085.jpeg',
			'https://images.pexels.com/photos/357756/pexels-photo-357756.jpeg',
			'https://images.pexels.com/photos/461428/pexels-photo-461428.jpeg',
		],
		distance: 4.2,
		address: {
			street: 'Carrer de Provença',
			number: '287',
			additionalInformation: '',
			postalCode: '08037',
			city: 'Barcelona',
			country: 'España',
			coordinates: {
				latitude: 41.3956,
				longitude: 2.1619,
			},
			formattedAddress: 'Carrer de Provença, 287, 08037 Barcelona, España',
		},
		tags: [
			RestaurantTag.RESERVATIONS,
			RestaurantTag.ROMANTIC,
			RestaurantTag.BUSINESS_FRIENDLY,
			RestaurantTag.AIR_CONDITIONING,
		],
		menus: [],
		phone: '+34 933 456 789',
		reservationLink: 'https://sakura-tokyo.com/reservas',
	},
	{
		id: '5',
		name: 'La Nonna Italiana',
		minimumPrice: 14,
		cuisineId: '3', // Italian
		rating: 4.3,
		mainImage:
			'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg',
		profileImage:
			'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg',
		images: [
			'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg',
			'https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg',
			'https://images.pexels.com/photos/699953/pexels-photo-699953.jpeg',
		],
		distance: 2.8,
		address: {
			street: 'Carrer de Muntaner',
			number: '156',
			additionalInformation: 'Entresol 2',
			postalCode: '08036',
			city: 'Barcelona',
			country: 'España',
			coordinates: {
				latitude: 41.3889,
				longitude: 2.1515,
			},
			formattedAddress:
				'Carrer de Muntaner, 156, Entresol 2, 08036 Barcelona, España',
		},
		tags: [
			RestaurantTag.FAMILY_FRIENDLY,
			RestaurantTag.VEGETARIAN,
			RestaurantTag.OUTDOOR_SEATING,
			RestaurantTag.WIFI,
		],
		menus: [],
		phone: '+34 934 567 890',
	},
	{
		id: '6',
		name: 'Mumbai Spice',
		minimumPrice: 13,
		cuisineId: '7', // Indian
		rating: 4.4,
		mainImage:
			'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg',
		profileImage:
			'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg',
		images: [
			'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg',
			'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
			'https://images.pexels.com/photos/2474658/pexels-photo-2474658.jpeg',
		],
		distance: 3.5,
		address: {
			street: 'Carrer de Balmes',
			number: '89',
			additionalInformation: 'Local 1',
			postalCode: '08008',
			city: 'Barcelona',
			country: 'España',
			coordinates: {
				latitude: 41.3926,
				longitude: 2.1589,
			},
			formattedAddress:
				'Carrer de Balmes, 89, Local 1, 08008 Barcelona, España',
		},
		tags: [
			RestaurantTag.SPICY,
			RestaurantTag.VEGETARIAN,
			RestaurantTag.VEGAN,
			RestaurantTag.HALAL,
			RestaurantTag.GLUTEN_FREE,
		],
		menus: [],
		phone: '+34 935 678 901',
	},
	{
		id: '7',
		name: 'Bangkok Street',
		minimumPrice: 11,
		cuisineId: '8', // Thai
		rating: 4.2,
		mainImage:
			'https://images.pexels.com/photos/12153467/pexels-photo-12153467.jpeg',
		profileImage:
			'https://images.pexels.com/photos/12153467/pexels-photo-12153467.jpeg',
		images: [
			'https://images.pexels.com/photos/12153467/pexels-photo-12153467.jpeg',
			'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
			'https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg',
		],
		distance: 4.1,
		address: {
			street: 'Carrer del Consell de Cent',
			number: '345',
			additionalInformation: '',
			postalCode: '08007',
			city: 'Barcelona',
			country: 'España',
			coordinates: {
				latitude: 41.3901,
				longitude: 2.1645,
			},
			formattedAddress:
				'Carrer del Consell de Cent, 345, 08007 Barcelona, España',
		},
		tags: [
			RestaurantTag.SPICY,
			RestaurantTag.VEGETARIAN,
			RestaurantTag.VEGAN,
			RestaurantTag.GLUTEN_FREE,
			RestaurantTag.WIFI,
		],
		menus: [],
		phone: '+34 936 789 012',
	},
	{
		id: '8',
		name: 'Seoul Kitchen',
		minimumPrice: 16,
		cuisineId: '9', // Korean
		rating: 4.6,
		mainImage:
			'https://images.pexels.com/photos/12973148/pexels-photo-12973148.jpeg',
		profileImage:
			'https://images.pexels.com/photos/12973148/pexels-photo-12973148.jpeg',
		images: [
			'https://images.pexels.com/photos/12973148/pexels-photo-12973148.jpeg',
			'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
			'https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg',
		],
		distance: 5.2,
		address: {
			street: 'Carrer de Girona',
			number: '78',
			additionalInformation: '1º 1ª',
			postalCode: '08009',
			city: 'Barcelona',
			country: 'España',
			coordinates: {
				latitude: 41.4001,
				longitude: 2.1701,
			},
			formattedAddress: 'Carrer de Girona, 78, 1º 1ª, 08009 Barcelona, España',
		},
		tags: [
			RestaurantTag.SPICY,
			RestaurantTag.RESERVATIONS,
			RestaurantTag.BUSINESS_FRIENDLY,
			RestaurantTag.AIR_CONDITIONING,
		],
		menus: [],
		phone: '+34 937 890 123',
		reservationLink: 'https://seoul-kitchen.com/booking',
	},
	{
		id: '9',
		name: 'Brooklyn Diner',
		minimumPrice: 17,
		cuisineId: '5', // American
		rating: 4.1,
		mainImage:
			'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg',
		profileImage:
			'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg',
		images: [
			'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg',
			'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
			'https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg',
		],
		distance: 3.7,
		address: {
			street: 'Passeig de Gràcia',
			number: '92',
			additionalInformation: 'Planta Baja',
			postalCode: '08008',
			city: 'Barcelona',
			country: 'España',
			coordinates: {
				latitude: 41.3956,
				longitude: 2.1619,
			},
			formattedAddress:
				'Passeig de Gràcia, 92, Planta Baja, 08008 Barcelona, España',
		},
		tags: [
			RestaurantTag.FAMILY_FRIENDLY,
			RestaurantTag.OUTDOOR_SEATING,
			RestaurantTag.LIVE_MUSIC,
			RestaurantTag.WIFI,
			RestaurantTag.PET_FRIENDLY,
		],
		menus: [],
		phone: '+34 938 901 234',
	},
	{
		id: '10',
		name: 'Le Petit Bistrot',
		minimumPrice: 25,
		cuisineId: '10', // Haute cuisine
		rating: 4.9,
		mainImage:
			'https://images.unsplash.com/photo-1577106263724-2c8e03bfe9cf?fm=jpg&q=60&w=3000',
		profileImage:
			'https://images.unsplash.com/photo-1577106263724-2c8e03bfe9cf?fm=jpg&q=60&w=3000',
		images: [
			'https://images.unsplash.com/photo-1577106263724-2c8e03bfe9cf?fm=jpg&q=60&w=3000',
			'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
			'https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg',
		],
		distance: 6.1,
		address: {
			street: 'Carrer de la Diputació',
			number: '234',
			additionalInformation: 'Principal',
			postalCode: '08007',
			city: 'Barcelona',
			country: 'España',
			coordinates: {
				latitude: 41.3889,
				longitude: 2.1634,
			},
			formattedAddress:
				'Carrer de la Diputació, 234, Principal, 08007 Barcelona, España',
		},
		tags: [
			RestaurantTag.ROMANTIC,
			RestaurantTag.BUSINESS_FRIENDLY,
			RestaurantTag.RESERVATIONS,
			RestaurantTag.AIR_CONDITIONING,
			RestaurantTag.WIFI,
		],
		menus: [],
		phone: '+34 939 012 345',
		reservationLink: 'https://lepetitbistrot.com/reservations',
	},
];

export const allCuisines: Cuisine[] = [
	{
		id: '1',
		name: {
			en_US: 'Mediterranean',
			es_ES: 'Mediterráneo',
			ca_ES: 'Mediterrani',
			fr_FR: 'Méditerranéen',
		},
		image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
	},
	{
		id: '2',
		name: {
			en_US: 'Japanese',
			es_ES: 'Japonés',
			ca_ES: 'Japonès',
			fr_FR: 'Japonais',
		},
		image:
			'https://images.pexels.com/photos/2098085/pexels-photo-2098085.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
	},
	{
		id: '3',
		name: {
			en_US: 'Italian',
			es_ES: 'Italiano',
			ca_ES: 'Italià',
			fr_FR: 'Italien',
		},
		image: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg',
	},
	{
		id: '4',
		name: {
			en_US: 'Mexican',
			es_ES: 'Mexicano',
			ca_ES: 'Mexicà',
			fr_FR: 'Mexicain',
		},
		image: 'https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg',
	},
	{
		id: '5',
		name: {
			en_US: 'American',
			es_ES: 'Americano',
			ca_ES: 'Americà',
			fr_FR: 'Américain',
		},
		image:
			'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
	},
	{
		id: '6',
		name: {
			en_US: 'Chinese',
			es_ES: 'Chino',
			ca_ES: 'Xinès',
			fr_FR: 'Chinois',
		},
		image:
			'https://images.pexels.com/photos/1907228/pexels-photo-1907228.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
	},
	{
		id: '7',
		name: {
			en_US: 'Indian',
			es_ES: 'Indio',
			ca_ES: 'Indi',
			fr_FR: 'Indien',
		},
		image:
			'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
	},
	{
		id: '8',
		name: {
			en_US: 'Thai',
			es_ES: 'Tailandés',
			ca_ES: 'Tailandès',
			fr_FR: 'Thaïlandais',
		},
		image:
			'https://images.pexels.com/photos/12153467/pexels-photo-12153467.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
	},
	{
		id: '9',
		name: {
			en_US: 'Korean',
			es_ES: 'Coreano',
			ca_ES: 'Coreà',
			fr_FR: 'Coréen',
		},
		image:
			'https://images.pexels.com/photos/12973148/pexels-photo-12973148.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
	},
	{
		id: '10',
		name: {
			en_US: 'Haute cuisine',
			es_ES: 'Alta cocina',
			ca_ES: 'Alta cuina',
			fr_FR: 'Haute cuisine',
		},
		image:
			'https://images.unsplash.com/photo-1577106263724-2c8e03bfe9cf?fm=jpg&q=60&w=3000',
	},
];

// Mock data - en producción esto vendría de una API
export const getCuisineById = (id: string): Cuisine | undefined => {
	return allCuisines.find((r) => r.id === id);
};

// Mock data - en producción esto vendría de una API
export const getRestaurantById = (id: string): Restaurant | undefined => {
	return allRestaurants.find((r) => r.id === id);
};

export const getMenusByRestaurantId = (id: string): MenuData[] => {
	const menuMap: Record<string, MenuData[]> = {
		// Sant Francesc Restaurant - Mediterranean
		'1': [
			{
				id: '1',
				name: 'Menú mediodía',
				startTime: '12:00',
				endTime: '16:00',
				days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
				price: 12.95,
				firstCoursesToShare: false,
				secondCoursesToShare: false,
				dessertsToShare: false,
				includesBread: true,
				drinks: { water: true, wine: false, softDrinks: false, beer: false },
				includesCoffeeAndDessert: 'dessert',
				minimumPeople: 1,
				hasMinimumPeople: false,
				dishes: [
					{
						id: '1',
						name: 'Ensalada César',
						description:
							'Lechuga romana y trozos de pan tostado con jugo de limón, aceite de oliva, huevo, salsa Worcestershire, anchoas, ajo, mostaza de Dijón, queso parmesano y pimienta negra.',
						extraPrice: 0,
						category: DishCategory.APPETIZERS,
						isVegetarian: true,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '2',
						name: 'Gazpacho',
						description:
							'Piña, jícama y mango, jugo de limón, cebolla, chile verde picado, jugo de naranja, un toque de vinagre y sal al gusto.',
						extraPrice: 0,
						category: DishCategory.APPETIZERS,
						isVegetarian: true,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: true,
					},
					{
						id: '3',
						name: 'Ensalada tradicional',
						description:
							'Tomates, cebollas, papas y atún, con el toque picante de la Pimienta Negra molida Alicante y los sabores algo alimonados y herbáceos del Tomillo, el Perejil deshidratado y el Romero Alicante.',
						extraPrice: 0,
						category: DishCategory.APPETIZERS,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: true,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '4',
						name: 'Sopa de cebolla',
						description:
							'Cebolla, vino blanco, mantequilla, harina de trigo, queso emmental rallado, pan baguette.',
						extraPrice: 1.5,
						category: DishCategory.APPETIZERS,
						isVegetarian: true,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '5',
						name: 'Salmón a la plancha',
						description:
							'Salmón fresco a la plancha con verduras de temporada y salsa de limón.',
						extraPrice: 0,
						category: DishCategory.SECOND_COURSES,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: false,
					},
					{
						id: '6',
						name: 'Paella Valenciana',
						description:
							'Arroz bomba, pollo, conejo, judía verde, garrofón, tomate, azafrán.',
						extraPrice: 3.0,
						category: DishCategory.SECOND_COURSES,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: false,
					},
					{
						id: '7',
						name: 'Crema Catalana',
						description: 'Postre tradicional catalán con crema quemada.',
						extraPrice: 0,
						category: DishCategory.DESSERTS,
						isVegetarian: true,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '8',
						name: 'Tiramisú',
						description: 'Postre italiano con café, mascarpone y cacao.',
						extraPrice: 0,
						category: DishCategory.DESSERTS,
						isVegetarian: true,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
				],
			},
			{
				id: '2',
				name: 'Menú cena',
				startTime: '19:00',
				endTime: '23:00',
				days: [
					'monday',
					'tuesday',
					'wednesday',
					'thursday',
					'friday',
					'saturday',
				],
				price: 18.95,
				firstCoursesToShare: true,
				secondCoursesToShare: false,
				dessertsToShare: true,
				includesBread: true,
				drinks: { water: true, wine: true, softDrinks: false, beer: false },
				includesCoffeeAndDessert: 'both',
				minimumPeople: 2,
				hasMinimumPeople: true,
				dishes: [
					{
						id: '9',
						name: 'Selección de tapas',
						description:
							'Selección variada de tapas tradicionales españolas y mediterráneas.',
						extraPrice: 2,
						category: DishCategory.APPETIZERS,
						isVegetarian: false,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '10',
						name: 'Tabla de quesos',
						description:
							'Selección de quesos artesanos españoles con frutos secos y mermeladas.',
						extraPrice: 0,
						category: DishCategory.APPETIZERS,
						isVegetarian: true,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '11',
						name: 'Carré de cordero',
						description:
							'Carré de cordero con hierbas de Provenza y patatas confitadas.',
						extraPrice: 3.0,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: true,
						isGlutenFree: true,
						isVegan: false,
					},
					{
						id: '12',
						name: 'Lubina',
						description: 'Lubina salvaje a la sal con verduras de temporada.',
						extraPrice: 0,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: false,
					},
				],
			},
			{
				id: '3',
				name: 'Especial fin de semana',
				startTime: '19:00',
				endTime: '23:30',
				days: ['saturday', 'sunday'],
				price: 22.95,
				firstCoursesToShare: false,
				secondCoursesToShare: false,
				dessertsToShare: false,
				includesBread: true,
				drinks: { water: true, wine: true, softDrinks: true, beer: false },
				includesCoffeeAndDessert: 'both',
				minimumPeople: 1,
				hasMinimumPeople: false,
				dishes: [
					{
						id: '13',
						name: 'Ostras',
						description: 'Ostras frescas de la costa con limón y chalota.',
						extraPrice: 4,
						category: DishCategory.APPETIZERS,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: false,
					},
					{
						id: '14',
						name: 'Langosta',
						description:
							'Langosta de la costa con mantequilla de hierbas aromáticas.',
						extraPrice: 5,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: false,
					},
				],
			},
		],

		// Tika Tacos - Mexican
		'2': [
			{
				id: '4',
				name: 'Menú Taco Tuesday',
				startTime: '12:00',
				endTime: '23:00',
				days: ['tuesday'],
				price: 9.95,
				firstCoursesToShare: true,
				secondCoursesToShare: true,
				dessertsToShare: false,
				includesBread: false,
				drinks: { water: false, wine: false, softDrinks: true, beer: true },
				includesCoffeeAndDessert: 'none',
				minimumPeople: 1,
				hasMinimumPeople: false,
				dishes: [
					{
						id: '15',
						name: 'Guacamole con nachos',
						description:
							'Guacamole fresco con aguacates maduros, lima, cilantro y nachos crujientes.',
						extraPrice: 0,
						category: DishCategory.APPETIZERS,
						isVegetarian: true,
						isLactoseFree: true,
						isSpicy: true,
						isGlutenFree: true,
						isVegan: true,
					},
					{
						id: '16',
						name: 'Tacos de pollo',
						description:
							'Tres tacos de pollo marinado con pico de gallo y crema agria.',
						extraPrice: 0,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: false,
						isSpicy: true,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '17',
						name: 'Tacos vegetarianos',
						description:
							'Tres tacos con frijoles negros, aguacate, queso y salsa verde.',
						extraPrice: 0,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: true,
						isLactoseFree: false,
						isSpicy: true,
						isGlutenFree: false,
						isVegan: false,
					},
				],
			},
			{
				id: '5',
				name: 'Menú completo',
				startTime: '12:00',
				endTime: '23:00',
				days: ['wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
				price: 14.95,
				firstCoursesToShare: true,
				secondCoursesToShare: false,
				dessertsToShare: true,
				includesBread: false,
				drinks: { water: true, wine: false, softDrinks: true, beer: true },
				includesCoffeeAndDessert: 'dessert',
				minimumPeople: 1,
				hasMinimumPeople: false,
				dishes: [
					{
						id: '18',
						name: 'Ceviche de pescado',
						description:
							'Pescado fresco marinado en lima con cebolla morada y cilantro.',
						extraPrice: 2,
						category: DishCategory.APPETIZERS,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: true,
						isGlutenFree: true,
						isVegan: false,
					},
					{
						id: '19',
						name: 'Quesadilla de queso',
						description: 'Quesadilla gigante con queso Oaxaca y pimientos.',
						extraPrice: 0,
						category: DishCategory.APPETIZERS,
						isVegetarian: true,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '20',
						name: 'Burrito de carne asada',
						description:
							'Burrito grande con carne asada, arroz, frijoles y guacamole.',
						extraPrice: 0,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: true,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '21',
						name: 'Enchiladas verdes',
						description:
							'Tres enchiladas con pollo y salsa verde, cubiertas con queso.',
						extraPrice: 1,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: false,
						isSpicy: true,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '22',
						name: 'Flan casero',
						description: 'Flan tradicional mexicano con caramelo.',
						extraPrice: 0,
						category: DishCategory.DESSERTS,
						isVegetarian: true,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: false,
					},
				],
			},
		],

		// El gran sol - Chinese
		'3': [
			{
				id: '6',
				name: 'Menú ejecutivo',
				startTime: '12:00',
				endTime: '16:00',
				days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
				price: 8.95,
				firstCoursesToShare: false,
				secondCoursesToShare: false,
				dessertsToShare: false,
				includesBread: false,
				drinks: { water: true, wine: false, softDrinks: true, beer: false },
				includesCoffeeAndDessert: 'none',
				minimumPeople: 1,
				hasMinimumPeople: false,
				dishes: [
					{
						id: '23',
						name: 'Sopa wonton',
						description:
							'Sopa tradicional con dumplings rellenos de cerdo y verduras.',
						extraPrice: 0,
						category: DishCategory.APPETIZERS,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '24',
						name: 'Rollitos de primavera',
						description:
							'Rollitos crujientes con verduras frescas y salsa agridulce.',
						extraPrice: 0,
						category: DishCategory.APPETIZERS,
						isVegetarian: true,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: true,
					},
					{
						id: '25',
						name: 'Pollo al curry',
						description: 'Pollo salteado con curry suave y arroz blanco.',
						extraPrice: 0,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: true,
						isGlutenFree: true,
						isVegan: false,
					},
					{
						id: '26',
						name: 'Ternera con brócoli',
						description:
							'Ternera tierna salteada con brócoli fresco y salsa de soja.',
						extraPrice: 0,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
				],
			},
			{
				id: '7',
				name: 'Menú familiar',
				startTime: '19:00',
				endTime: '23:00',
				days: ['friday', 'saturday', 'sunday'],
				price: 16.95,
				firstCoursesToShare: true,
				secondCoursesToShare: true,
				dessertsToShare: true,
				includesBread: false,
				drinks: { water: true, wine: false, softDrinks: true, beer: true },
				includesCoffeeAndDessert: 'dessert',
				minimumPeople: 4,
				hasMinimumPeople: true,
				dishes: [
					{
						id: '27',
						name: 'Surtido de dim sum',
						description:
							'Variedad de dim sum al vapor con diferentes rellenos.',
						extraPrice: 3,
						category: DishCategory.APPETIZERS,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '28',
						name: 'Pato laqueado',
						description:
							'Pato laqueado tradicional con pancakes y salsa hoisin.',
						extraPrice: 5,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '29',
						name: 'Arroz frito tres delicias',
						description: 'Arroz frito con jamón, huevo y guisantes.',
						extraPrice: 0,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: false,
					},
					{
						id: '30',
						name: 'Helado frito',
						description: 'Helado de vainilla envuelto en masa crujiente.',
						extraPrice: 0,
						category: DishCategory.DESSERTS,
						isVegetarian: true,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
				],
			},
		],

		// Sakura Tokyo - Japanese
		'4': [
			{
				id: '8',
				name: 'Menú Bento',
				startTime: '12:00',
				endTime: '15:00',
				days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
				price: 16.95,
				firstCoursesToShare: false,
				secondCoursesToShare: false,
				dessertsToShare: false,
				includesBread: false,
				drinks: { water: true, wine: false, softDrinks: false, beer: false },
				includesCoffeeAndDessert: 'none',
				minimumPeople: 1,
				hasMinimumPeople: false,
				dishes: [
					{
						id: '31',
						name: 'Miso shiru',
						description: 'Sopa miso tradicional con tofu y algas wakame.',
						extraPrice: 0,
						category: DishCategory.APPETIZERS,
						isVegetarian: true,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: true,
					},
					{
						id: '32',
						name: 'Edamame',
						description: 'Vainas de soja hervidas con sal marina.',
						extraPrice: 0,
						category: DishCategory.APPETIZERS,
						isVegetarian: true,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: true,
					},
					{
						id: '33',
						name: 'Salmón teriyaki',
						description:
							'Salmón a la plancha con salsa teriyaki y arroz japonés.',
						extraPrice: 0,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '34',
						name: 'Chicken katsu',
						description: 'Pechuga de pollo empanada con salsa tonkatsu.',
						extraPrice: 0,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
				],
			},
			{
				id: '9',
				name: 'Menú Omakase',
				startTime: '19:30',
				endTime: '22:00',
				days: ['thursday', 'friday', 'saturday'],
				price: 45.0,
				firstCoursesToShare: false,
				secondCoursesToShare: false,
				dessertsToShare: false,
				includesBread: false,
				drinks: { water: true, wine: true, softDrinks: false, beer: true },
				includesCoffeeAndDessert: 'both',
				minimumPeople: 2,
				hasMinimumPeople: true,
				dishes: [
					{
						id: '35',
						name: 'Selección de sashimi',
						description:
							'Sashimi premium del día con wasabi y jengibre encurtido.',
						extraPrice: 8,
						category: DishCategory.APPETIZERS,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: false,
					},
					{
						id: '36',
						name: 'Sushi del chef',
						description:
							'Selección de sushi preparado por el chef con pescado del día.',
						extraPrice: 10,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '37',
						name: 'Wagyu tataki',
						description: 'Wagyu sellado ligeramente con salsa ponzu.',
						extraPrice: 15,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '38',
						name: 'Mochi de té verde',
						description: 'Mochi casero relleno de crema de té verde.',
						extraPrice: 0,
						category: DishCategory.DESSERTS,
						isVegetarian: true,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: false,
					},
				],
			},
		],

		// La Nonna Italiana - Italian
		'5': [
			{
				id: '10',
				name: 'Menú pranzo',
				startTime: '12:00',
				endTime: '16:00',
				days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
				price: 13.5,
				firstCoursesToShare: false,
				secondCoursesToShare: false,
				dessertsToShare: false,
				includesBread: true,
				drinks: { water: true, wine: false, softDrinks: false, beer: false },
				includesCoffeeAndDessert: 'coffee',
				minimumPeople: 1,
				hasMinimumPeople: false,
				dishes: [
					{
						id: '39',
						name: 'Bruschetta al pomodoro',
						description:
							'Pan tostado con tomate fresco, albahaca y aceite de oliva.',
						extraPrice: 0,
						category: DishCategory.APPETIZERS,
						isVegetarian: true,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: true,
					},
					{
						id: '40',
						name: 'Carpaccio di manzo',
						description:
							'Láminas finas de ternera con rúcula, parmesano y limón.',
						extraPrice: 2,
						category: DishCategory.APPETIZERS,
						isVegetarian: false,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: false,
					},
					{
						id: '41',
						name: 'Spaghetti carbonara',
						description:
							'Pasta tradicional con huevo, panceta, pecorino y pimienta negra.',
						extraPrice: 0,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '42',
						name: 'Pizza Margherita',
						description:
							'Pizza clásica con tomate, mozzarella di bufala y albahaca.',
						extraPrice: 0,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: true,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '43',
						name: 'Panna cotta',
						description: 'Panna cotta de vainilla con coulis de frutos rojos.',
						extraPrice: 0,
						category: DishCategory.DESSERTS,
						isVegetarian: true,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: false,
					},
				],
			},
			{
				id: '11',
				name: 'Menú domenica',
				startTime: '13:00',
				endTime: '23:00',
				days: ['saturday', 'sunday'],
				price: 24.95,
				firstCoursesToShare: true,
				secondCoursesToShare: false,
				dessertsToShare: true,
				includesBread: true,
				drinks: { water: true, wine: true, softDrinks: false, beer: false },
				includesCoffeeAndDessert: 'both',
				minimumPeople: 2,
				hasMinimumPeople: true,
				dishes: [
					{
						id: '44',
						name: 'Antipasti misti',
						description: 'Selección de embutidos, quesos y verduras en aceite.',
						extraPrice: 3,
						category: DishCategory.APPETIZERS,
						isVegetarian: false,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '45',
						name: 'Risotto ai funghi porcini',
						description: 'Risotto cremoso con setas porcini y parmesano.',
						extraPrice: 0,
						category: DishCategory.FIRST_COURSES,
						isVegetarian: true,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: false,
					},
					{
						id: '46',
						name: 'Osso buco alla milanese',
						description:
							'Jarrete de ternera estofado con risotto alla milanese.',
						extraPrice: 4,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: false,
					},
					{
						id: '47',
						name: 'Tiramisu della casa',
						description: 'Tiramisú casero con mascarpone y café espresso.',
						extraPrice: 0,
						category: DishCategory.DESSERTS,
						isVegetarian: true,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
				],
			},
		],

		// Mumbai Spice - Indian
		'6': [
			{
				id: '12',
				name: 'Menú Thali',
				startTime: '12:00',
				endTime: '22:00',
				days: [
					'monday',
					'tuesday',
					'wednesday',
					'thursday',
					'friday',
					'saturday',
					'sunday',
				],
				price: 11.95,
				firstCoursesToShare: false,
				secondCoursesToShare: false,
				dessertsToShare: false,
				includesBread: true,
				drinks: { water: true, wine: false, softDrinks: true, beer: false },
				includesCoffeeAndDessert: 'none',
				minimumPeople: 1,
				hasMinimumPeople: false,
				dishes: [
					{
						id: '48',
						name: 'Samosas vegetales',
						description:
							'Empanadillas crujientes rellenas de verduras especiadas.',
						extraPrice: 0,
						category: DishCategory.APPETIZERS,
						isVegetarian: true,
						isLactoseFree: true,
						isSpicy: true,
						isGlutenFree: false,
						isVegan: true,
					},
					{
						id: '49',
						name: 'Pollo tikka masala',
						description:
							'Pollo marinado en yogur y especias con salsa cremosa de tomate.',
						extraPrice: 0,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: false,
						isSpicy: true,
						isGlutenFree: true,
						isVegan: false,
					},
					{
						id: '50',
						name: 'Dal de lentejas',
						description: 'Curry de lentejas rojas con especias tradicionales.',
						extraPrice: 0,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: true,
						isLactoseFree: true,
						isSpicy: true,
						isGlutenFree: true,
						isVegan: true,
					},
					{
						id: '51',
						name: 'Arroz basmati',
						description: 'Arroz basmati aromático cocido al vapor.',
						extraPrice: 0,
						category: DishCategory.SIDES,
						isVegetarian: true,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: true,
					},
					{
						id: '52',
						name: 'Naan bread',
						description: 'Pan indio tradicional horneado en tandoor.',
						extraPrice: 0,
						category: DishCategory.SIDES,
						isVegetarian: true,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
				],
			},
		],

		// Bangkok Street - Thai
		'7': [
			{
				id: '13',
				name: 'Menú Street Food',
				startTime: '12:00',
				endTime: '23:00',
				days: [
					'monday',
					'tuesday',
					'wednesday',
					'thursday',
					'friday',
					'saturday',
					'sunday',
				],
				price: 10.5,
				firstCoursesToShare: true,
				secondCoursesToShare: false,
				dessertsToShare: false,
				includesBread: false,
				drinks: { water: true, wine: false, softDrinks: true, beer: true },
				includesCoffeeAndDessert: 'none',
				minimumPeople: 1,
				hasMinimumPeople: false,
				dishes: [
					{
						id: '53',
						name: 'Tom yum kung',
						description:
							'Sopa picante y agria con gambas, setas y hierba limón.',
						extraPrice: 1,
						category: DishCategory.APPETIZERS,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: true,
						isGlutenFree: true,
						isVegan: false,
					},
					{
						id: '54',
						name: 'Spring rolls frescos',
						description: 'Rollitos frescos con verduras y hierbas aromáticas.',
						extraPrice: 0,
						category: DishCategory.APPETIZERS,
						isVegetarian: true,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: true,
					},
					{
						id: '55',
						name: 'Pad Thai de pollo',
						description:
							'Fideos de arroz salteados con pollo, huevo y salsa tamarindo.',
						extraPrice: 0,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: true,
						isGlutenFree: true,
						isVegan: false,
					},
					{
						id: '56',
						name: 'Green curry vegetariano',
						description:
							'Curry verde con verduras de temporada y leche de coco.',
						extraPrice: 0,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: true,
						isLactoseFree: true,
						isSpicy: true,
						isGlutenFree: true,
						isVegan: true,
					},
				],
			},
		],

		// Seoul Kitchen - Korean
		'8': [
			{
				id: '14',
				name: 'Menú BBQ',
				startTime: '18:00',
				endTime: '23:00',
				days: ['thursday', 'friday', 'saturday', 'sunday'],
				price: 19.95,
				firstCoursesToShare: true,
				secondCoursesToShare: true,
				dessertsToShare: false,
				includesBread: false,
				drinks: { water: true, wine: false, softDrinks: true, beer: true },
				includesCoffeeAndDessert: 'none',
				minimumPeople: 2,
				hasMinimumPeople: true,
				dishes: [
					{
						id: '57',
						name: 'Kimchi',
						description:
							'Col china fermentada con especias coreanas tradicionales.',
						extraPrice: 0,
						category: DishCategory.APPETIZERS,
						isVegetarian: true,
						isLactoseFree: true,
						isSpicy: true,
						isGlutenFree: true,
						isVegan: true,
					},
					{
						id: '58',
						name: 'Bulgogi',
						description: 'Ternera marinada a la parrilla con verduras y arroz.',
						extraPrice: 2,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: true,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '59',
						name: 'Bibimbap',
						description:
							'Arroz con verduras salteadas, huevo frito y salsa gochujang.',
						extraPrice: 0,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: true,
						isLactoseFree: true,
						isSpicy: true,
						isGlutenFree: false,
						isVegan: false,
					},
				],
			},
			{
				id: '15',
				name: 'Menú Hotpot',
				startTime: '19:00',
				endTime: '22:30',
				days: ['friday', 'saturday'],
				price: 24.95,
				firstCoursesToShare: true,
				secondCoursesToShare: true,
				dessertsToShare: false,
				includesBread: false,
				drinks: { water: true, wine: false, softDrinks: true, beer: true },
				includesCoffeeAndDessert: 'none',
				minimumPeople: 4,
				hasMinimumPeople: true,
				dishes: [
					{
						id: '60',
						name: 'Surtido banchan',
						description: 'Variedad de acompañamientos coreanos tradicionales.',
						extraPrice: 0,
						category: DishCategory.APPETIZERS,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: true,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '61',
						name: 'Korean hotpot',
						description: 'Olla caliente coreana con carnes, verduras y tofu.',
						extraPrice: 5,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: true,
						isGlutenFree: false,
						isVegan: false,
					},
				],
			},
		],

		// Brooklyn Diner - American
		'9': [
			{
				id: '16',
				name: 'Brunch Weekend',
				startTime: '10:00',
				endTime: '16:00',
				days: ['saturday', 'sunday'],
				price: 15.95,
				firstCoursesToShare: false,
				secondCoursesToShare: false,
				dessertsToShare: false,
				includesBread: false,
				drinks: { water: false, wine: false, softDrinks: true, beer: false },
				includesCoffeeAndDessert: 'coffee',
				minimumPeople: 1,
				hasMinimumPeople: false,
				dishes: [
					{
						id: '62',
						name: 'Buffalo wings',
						description: 'Alitas de pollo picantes con salsa blue cheese.',
						extraPrice: 2,
						category: DishCategory.APPETIZERS,
						isVegetarian: false,
						isLactoseFree: false,
						isSpicy: true,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '63',
						name: 'Classic burger',
						description:
							'Hamburguesa clásica con lechuga, tomate, cebolla y papas fritas.',
						extraPrice: 0,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '64',
						name: 'BBQ ribs',
						description: 'Costillas a la barbacoa con salsa BBQ casera.',
						extraPrice: 3,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '65',
						name: 'Apple pie',
						description: 'Tarta de manzana americana con helado de vainilla.',
						extraPrice: 0,
						category: DishCategory.DESSERTS,
						isVegetarian: true,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
				],
			},
			{
				id: '17',
				name: 'Dinner Special',
				startTime: '18:00',
				endTime: '23:00',
				days: ['wednesday', 'thursday', 'friday', 'saturday'],
				price: 21.95,
				firstCoursesToShare: true,
				secondCoursesToShare: false,
				dessertsToShare: true,
				includesBread: false,
				drinks: { water: true, wine: true, softDrinks: true, beer: true },
				includesCoffeeAndDessert: 'both',
				minimumPeople: 1,
				hasMinimumPeople: false,
				dishes: [
					{
						id: '66',
						name: 'Caesar salad',
						description: 'Ensalada César con pollo a la parrilla y crutones.',
						extraPrice: 0,
						category: DishCategory.APPETIZERS,
						isVegetarian: false,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '67',
						name: 'New York steak',
						description: 'Filete de ternera a la parrilla con puré de patatas.',
						extraPrice: 5,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: false,
					},
					{
						id: '68',
						name: 'Cheesecake',
						description:
							'Tarta de queso de Nueva York con coulis de frutos rojos.',
						extraPrice: 0,
						category: DishCategory.DESSERTS,
						isVegetarian: true,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
				],
			},
		],

		// Le Petit Bistrot - Haute cuisine
		'10': [
			{
				id: '18',
				name: 'Menu Dégustation',
				startTime: '19:30',
				endTime: '22:30',
				days: ['tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
				price: 65.0,
				firstCoursesToShare: false,
				secondCoursesToShare: false,
				dessertsToShare: false,
				includesBread: true,
				drinks: { water: true, wine: true, softDrinks: false, beer: false },
				includesCoffeeAndDessert: 'both',
				minimumPeople: 2,
				hasMinimumPeople: true,
				dishes: [
					{
						id: '69',
						name: 'Amuse-bouche',
						description: 'Selección de pequeños aperitivos del chef.',
						extraPrice: 0,
						category: DishCategory.APPETIZERS,
						isVegetarian: false,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '70',
						name: 'Foie gras mi-cuit',
						description: 'Foie gras semicocido con chutney de higos y brioche.',
						extraPrice: 12,
						category: DishCategory.APPETIZERS,
						isVegetarian: false,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '71',
						name: 'Sopa de trufa negra',
						description: 'Velouté de trufa negra con crema de parmesano.',
						extraPrice: 8,
						category: DishCategory.FIRST_COURSES,
						isVegetarian: true,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: false,
					},
					{
						id: '72',
						name: 'Lubina en costra de sal',
						description:
							'Lubina salvaje en costra de sal con verduras confitadas.',
						extraPrice: 0,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: false,
					},
					{
						id: '73',
						name: 'Cordero de Pirineos',
						description:
							'Carré de cordero con hierbas provenzales y ratatouille.',
						extraPrice: 10,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: false,
					},
					{
						id: '74',
						name: 'Selección de quesos',
						description: 'Tabla de quesos artesanos franceses con mermeladas.',
						extraPrice: 5,
						category: DishCategory.DESSERTS,
						isVegetarian: true,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '75',
						name: 'Soufflé Grand Marnier',
						description: 'Soufflé caliente de Grand Marnier con salsa inglesa.',
						extraPrice: 0,
						category: DishCategory.DESSERTS,
						isVegetarian: true,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '76',
						name: 'Mignardises',
						description: 'Pequeños dulces y chocolates artesanos.',
						extraPrice: 0,
						category: DishCategory.DESSERTS,
						isVegetarian: true,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
				],
			},
			{
				id: '19',
				name: 'Menu Business',
				startTime: '12:00',
				endTime: '15:00',
				days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
				price: 35.0,
				firstCoursesToShare: false,
				secondCoursesToShare: false,
				dessertsToShare: false,
				includesBread: true,
				drinks: { water: true, wine: true, softDrinks: false, beer: false },
				includesCoffeeAndDessert: 'both',
				minimumPeople: 1,
				hasMinimumPeople: false,
				dishes: [
					{
						id: '77',
						name: 'Terrina de pato',
						description: 'Terrina casera de pato con pistachos y pan tostado.',
						extraPrice: 0,
						category: DishCategory.APPETIZERS,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
					{
						id: '78',
						name: 'Salmón confit',
						description:
							'Salmón confitado a baja temperatura con puré de coliflor.',
						extraPrice: 2,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: false,
					},
					{
						id: '79',
						name: 'Magret de pato',
						description:
							'Magret de pato con salsa de cerezas y gratin dauphinoise.',
						extraPrice: 3,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: false,
					},
					{
						id: '80',
						name: 'Tarte Tatin',
						description:
							'Tarta invertida de manzana con helado de vainilla bourbon.',
						extraPrice: 0,
						category: DishCategory.DESSERTS,
						isVegetarian: true,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
				],
			},
		],
	};

	return menuMap[id] || [];
};

// Añadir al final de api/responses.ts

// Mock data para las reseñas del usuario actual
export const mockUserReviews: Review[] = [
	{
		id: '1',
		userId: 'current_user',
		userName: 'Tu Usuario',
		userAvatar: 'https://randomuser.me/api/portraits/men/10.jpg',
		rating: 5,
		comment:
			'Excelente comida tradicional, el ambiente es muy acogedor y el personal muy atento. La paella estaba espectacular.',
		date: '2024-06-15',
		photos: [
			'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=300',
			'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=300',
		],
		restaurantId: '1',
		restaurantName: 'Sant Francesc Restaurant',
		restaurantImage:
			'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
	},
	{
		id: '2',
		userId: 'current_user',
		userName: 'Tu Usuario',
		userAvatar: 'https://randomuser.me/api/portraits/men/10.jpg',
		rating: 4,
		comment:
			'Pescado fresco y buen servicio. Recomendado para una cena especial.',
		date: '2024-06-10',
		photos: [],
		restaurantId: '3',
		restaurantName: 'El gran sol',
		restaurantImage:
			'https://images.pexels.com/photos/1907228/pexels-photo-1907228.jpeg',
		restaurantResponse: {
			message:
				'Muchas gracias por tu comentario. Nos alegra que hayas disfrutado de la experiencia.',
			date: '2024-06-11',
		},
	},
	{
		id: '3',
		userId: 'current_user',
		userName: 'Tu Usuario',
		userAvatar: 'https://randomuser.me/api/portraits/men/10.jpg',
		rating: 4.5,
		comment:
			'Increíble experiencia gastronómica japonesa. El sushi estaba fresco y la presentación impecable.',
		date: '2024-06-05',
		photos: [
			'https://images.unsplash.com/photo-1563612116625-3012372fccce?w=300',
		],
		restaurantId: '4',
		restaurantName: 'Sakura Tokyo',
		restaurantImage:
			'https://images.pexels.com/photos/2098085/pexels-photo-2098085.jpeg',
	},
	{
		id: '4',
		userId: 'current_user',
		userName: 'Tu Usuario',
		userAvatar: 'https://randomuser.me/api/portraits/men/10.jpg',
		rating: 3.8,
		comment:
			'Buenas tapas tradicionales. Ambiente auténtico español aunque el servicio podría ser más rápido.',
		date: '2024-05-28',
		photos: [],
		restaurantId: '2',
		restaurantName: 'Tika Tacos',
		restaurantImage:
			'https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg',
	},
	{
		id: '5',
		userId: 'current_user',
		userName: 'Tu Usuario',
		userAvatar: 'https://randomuser.me/api/portraits/men/10.jpg',
		rating: 4.2,
		comment:
			'Perfecto para un desayuno o brunch. El café es excelente y los pasteles están deliciosos.',
		date: '2024-05-20',
		photos: [
			'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=300',
			'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=300',
		],
		restaurantId: '5',
		restaurantName: 'La Nonna Italiana',
		restaurantImage:
			'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg',
	},
	{
		id: '6',
		userId: 'current_user',
		userName: 'Tu Usuario',
		userAvatar: 'https://randomuser.me/api/portraits/men/10.jpg',
		rating: 5,
		comment:
			'El mejor curry de la ciudad. Los sabores son auténticos y las especias perfectamente balanceadas.',
		date: '2024-05-15',
		photos: [],
		restaurantId: '6',
		restaurantName: 'Mumbai Spice',
		restaurantImage:
			'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg',
		restaurantResponse: {
			message:
				'¡Gracias por tu reseña! Nos encanta saber que disfrutaste de nuestros platos auténticos.',
			date: '2024-05-16',
		},
	},
	{
		id: '7',
		userId: 'current_user',
		userName: 'Tu Usuario',
		userAvatar: 'https://randomuser.me/api/portraits/men/10.jpg',
		rating: 3.5,
		comment:
			'Comida tailandesa decente. El pad thai estaba bien pero he probado mejores. El lugar está bien para una cena casual.',
		date: '2024-05-10',
		photos: ['https://images.unsplash.com/photo-1562565652-a0d8f0c59eb4?w=300'],
		restaurantId: '7',
		restaurantName: 'Bangkok Street',
		restaurantImage:
			'https://images.pexels.com/photos/12153467/pexels-photo-12153467.jpeg',
	},
	{
		id: '8',
		userId: 'current_user',
		userName: 'Tu Usuario',
		userAvatar: 'https://randomuser.me/api/portraits/men/10.jpg',
		rating: 4.8,
		comment:
			'Experiencia de BBQ coreano increíble. La carne estaba tierna y bien marinada. Perfecto para ir en grupo.',
		date: '2024-05-05',
		photos: [
			'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=300',
			'https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=300',
		],
		restaurantId: '8',
		restaurantName: 'Seoul Kitchen',
		restaurantImage:
			'https://images.pexels.com/photos/12973148/pexels-photo-12973148.jpeg',
	},
	{
		id: '9',
		userId: 'current_user',
		userName: 'Tu Usuario',
		userAvatar: 'https://randomuser.me/api/portraits/men/10.jpg',
		rating: 3.2,
		comment:
			'Hamburguesas grandes pero un poco secas. Las patatas están bien. Servicio lento pero el ambiente es agradable.',
		date: '2024-04-25',
		photos: [],
		restaurantId: '9',
		restaurantName: 'Brooklyn Diner',
		restaurantImage:
			'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg',
	},
	{
		id: '10',
		userId: 'current_user',
		userName: 'Tu Usuario',
		userAvatar: 'https://randomuser.me/api/portraits/men/10.jpg',
		rating: 5,
		comment:
			'Una experiencia culinaria extraordinaria. Cada plato es una obra de arte. El servicio es impecable y la presentación sublime.',
		date: '2024-04-20',
		photos: [
			'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=300',
			'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=300',
			'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=300',
		],
		restaurantId: '10',
		restaurantName: 'Le Petit Bistrot',
		restaurantImage:
			'https://images.unsplash.com/photo-1577106263724-2c8e03bfe9cf?fm=jpg&q=60&w=3000',
		restaurantResponse: {
			message:
				'Merci beaucoup pour votre critique élogieuse! Nous sommes ravis que vous ayez apprécié notre cuisine.',
			date: '2024-04-21',
		},
	},
];

// Mock data para las reseñas del restaurante consultado
export const mockReviews: Review[] = [
	{
		id: '1',
		userId: 'user1',
		userName: 'María García',
		userAvatar: 'https://randomuser.me/api/portraits/women/1.jpg',
		rating: 5,
		comment:
			'Increíble experiencia! La comida estaba deliciosa y el servicio fue excepcional. Definitivamente volveré pronto.',
		date: '2024-12-10',
		photos: [
			'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=300',
			'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=300',
		],
		restaurantResponse: {
			message:
				'¡Muchas gracias por tu comentario María! Nos alegra mucho saber que disfrutaste de tu experiencia con nosotros.',
			date: '2024-12-11',
		},
		restaurantId: 'restaurant1',
		restaurantName: 'Restaurante Ejemplo',
		restaurantImage:
			'https://images.unsplash.com/photo-1542831371-5c8b3f6d7a2c?w=300',
	},
	{
		id: '2',
		userId: 'user2',
		userName: 'Carlos Rodríguez',
		userAvatar: 'https://randomuser.me/api/portraits/men/2.jpg',
		rating: 4.5,
		comment:
			'Muy buen restaurante, la comida está muy rica aunque tuvimos que esperar un poco. El ambiente es acogedor.',
		date: '2024-12-08',
		photos: [
			'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=300',
		],
		restaurantId: 'restaurant1',
		restaurantName: 'Restaurante Ejemplo',
		restaurantImage:
			'https://images.unsplash.com/photo-1542831371-5c8b3f6d7a2c?w=300',
	},
	{
		id: '3',
		userId: 'user3',
		userName: 'Ana Martínez',
		userAvatar: 'https://randomuser.me/api/portraits/women/3.jpg',
		rating: 4.8,
		comment:
			'Perfecta cena de aniversario. El personal fue muy atento y la decoración es preciosa. Los postres son espectaculares.',
		date: '2024-12-05',
		photos: [],
		restaurantId: 'restaurant1',
		restaurantName: 'Restaurante Ejemplo',
		restaurantImage:
			'https://images.unsplash.com/photo-1542831371-5c8b3f6d7a2c?w=300',
	},
	{
		id: '4',
		userId: 'user4',
		userName: 'David López',
		userAvatar: 'https://randomuser.me/api/portraits/men/4.jpg',
		rating: 2.5,
		comment:
			'La comida está bien pero esperaba más por el precio. El servicio podría mejorar un poco.',
		date: '2024-12-03',
		photos: [],
		restaurantResponse: {
			message:
				'Gracias por tu feedback David. Tomamos nota de tus comentarios para seguir mejorando nuestro servicio.',
			date: '2024-12-04',
		},
		restaurantId: 'restaurant1',
		restaurantName: 'Restaurante Ejemplo',
		restaurantImage:
			'https://images.unsplash.com/photo-1542831371-5c8b3f6d7a2c?w=300',
	},
	{
		id: '5',
		userId: 'user5',
		userName: 'Laura Fernández',
		userAvatar: 'https://randomuser.me/api/portraits/women/5.jpg',
		rating: 4.2,
		comment:
			'Una experiencia gastronómica increíble. Cada plato fue una sorpresa para el paladar. Altamente recomendado para una ocasión especial.',
		date: '2024-11-28',
		photos: [
			'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=300',
			'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=300',
			'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=300',
		],
		restaurantId: 'restaurant1',
		restaurantName: 'Restaurante Ejemplo',
		restaurantImage:
			'https://images.unsplash.com/photo-1542831371-5c8b3f6d7a2c?w=300',
	},
	{
		id: '6',
		userId: 'user6',
		userName: 'Roberto Silva',
		userAvatar: 'https://randomuser.me/api/portraits/men/6.jpg',
		rating: 1.5,
		comment:
			'Muy decepcionante. La comida llegó fría y el servicio fue muy lento. No recomiendo este lugar.',
		date: '2024-11-25',
		photos: [],
		restaurantId: 'restaurant1',
		restaurantName: 'Restaurante Ejemplo',
		restaurantImage:
			'https://images.unsplash.com/photo-1542831371-5c8b3f6d7a2c?w=300',
	},
];

// Mock data para restaurantes del usuario
export const mockUserRestaurants: Restaurant[] = [
	{
		id: 'user-rest-1',
		name: 'La Taberna del Abuelo',
		minimumPrice: 12,
		cuisineId: '1', // Mediterranean
		rating: 4.3,
		mainImage:
			'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
		profileImage:
			'https://visitbegur.cat/wp-content/uploads/2021/06/mooma-1024x813.jpg',
		images: [
			'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
			'https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg',
			'https://images.pexels.com/photos/1907228/pexels-photo-1907228.jpeg',
		],
		distance: 0,
		address: {
			street: 'Calle Mayor',
			number: '123',
			additionalInformation: 'Local 2',
			postalCode: '28001',
			city: 'Madrid',
			country: 'España',
			coordinates: {
				latitude: 40.4168,
				longitude: -3.7038,
			},
			formattedAddress: 'Calle Mayor, 123, Local 2, 28001 Madrid, España',
		},
		tags: [
			RestaurantTag.FAMILY_FRIENDLY,
			RestaurantTag.VEGETARIAN,
			RestaurantTag.OUTDOOR_SEATING,
			RestaurantTag.WIFI,
		],
		menus: [],
		phone: '+34 911 234 567',
		reservationLink: 'https://reservas.latabernaddelabuelo.com',
	},
	{
		id: 'user-rest-2',
		name: 'Bistro Mediterráneo',
		minimumPrice: 18,
		cuisineId: '1', // Mediterranean
		rating: 4.6,
		mainImage:
			'https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg',
		profileImage:
			'https://visitbegur.cat/wp-content/uploads/2021/06/mooma-1024x813.jpg',
		images: [
			'https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg',
			'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
			'https://images.pexels.com/photos/1907228/pexels-photo-1907228.jpeg',
		],
		distance: 0,
		address: {
			street: 'Avenida de la Paz',
			number: '45',
			additionalInformation: '2º A',
			postalCode: '08002',
			city: 'Barcelona',
			country: 'España',
			coordinates: {
				latitude: 41.3851,
				longitude: 2.1734,
			},
			formattedAddress: 'Avenida de la Paz, 45, 2º A, 08002 Barcelona, España',
		},
		tags: [
			RestaurantTag.ROMANTIC,
			RestaurantTag.BUSINESS_FRIENDLY,
			RestaurantTag.RESERVATIONS,
			RestaurantTag.AIR_CONDITIONING,
		],
		menus: [],
		phone: '+34 933 456 789',
		reservationLink: 'https://bistromediterraneo.opentable.com',
	},
	{
		id: 'user-rest-3',
		name: 'Café Central',
		minimumPrice: 8,
		cuisineId: '5', // American
		rating: 3.9,
		mainImage:
			'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg',
		profileImage:
			'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg',
		images: [
			'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg',
		],
		distance: 0,
		address: {
			street: 'Plaza de la Constitución',
			number: '8',
			additionalInformation: '',
			postalCode: '41001',
			city: 'Sevilla',
			country: 'España',
			coordinates: {
				latitude: 37.3886,
				longitude: -5.9823,
			},
			formattedAddress: 'Plaza de la Constitución, 8, 41001 Sevilla, España',
		},
		tags: [
			RestaurantTag.WIFI,
			RestaurantTag.OUTDOOR_SEATING,
			RestaurantTag.FAMILY_FRIENDLY,
		],
		menus: [],
		phone: '+34 954 123 456',
	},
];

// Estado de activación de restaurantes del usuario
export const mockUserRestaurantStatus: Record<string, { isActive: boolean }> = {
	'user-rest-1': { isActive: true },
	'user-rest-2': { isActive: true },
	'user-rest-3': { isActive: false },
};

// Función para obtener restaurantes del usuario
export const getUserRestaurants = (): Restaurant[] => {
	return mockUserRestaurants;
};

// Función para obtener un restaurante del usuario por ID
export const getUserRestaurantById = (id: string): Restaurant | undefined => {
	return mockUserRestaurants.find((restaurant) => restaurant.id === id);
};

// Función para obtener el estado de un restaurante del usuario
export const getUserRestaurantStatus = (id: string): { isActive: boolean } => {
	return mockUserRestaurantStatus[id] || { isActive: false };
};

// Función para actualizar el estado de un restaurante del usuario
export const updateUserRestaurantStatus = (
	id: string,
	isActive: boolean,
): void => {
	mockUserRestaurantStatus[id] = { isActive };
};

// Menús para los restaurantes del usuario
export const getUserRestaurantMenus = (id: string): MenuData[] => {
	const menuMap: Record<string, MenuData[]> = {
		'user-rest-1': [
			{
				id: 'user-menu-1',
				name: 'Menú del día',
				startTime: '13:00',
				endTime: '16:00',
				days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
				price: 12.95,
				firstCoursesToShare: false,
				secondCoursesToShare: false,
				dessertsToShare: false,
				includesBread: true,
				drinks: { water: true, wine: false, softDrinks: false, beer: false },
				includesCoffeeAndDessert: 'dessert',
				minimumPeople: 1,
				hasMinimumPeople: false,
				dishes: [
					{
						id: 'user-dish-1',
						name: 'Gazpacho andaluz',
						description: 'Gazpacho tradicional con verduras frescas',
						extraPrice: 0,
						category: DishCategory.APPETIZERS,
						isVegetarian: true,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: true,
					},
					{
						id: 'user-dish-2',
						name: 'Paella mixta',
						description: 'Paella con pollo, mariscos y verduras',
						extraPrice: 2,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: false,
					},
					{
						id: 'user-dish-3',
						name: 'Flan casero',
						description: 'Flan tradicional con caramelo',
						extraPrice: 0,
						category: DishCategory.DESSERTS,
						isVegetarian: true,
						isLactoseFree: false,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: false,
					},
				],
			},
		],
		'user-rest-2': [
			{
				id: 'user-menu-2',
				name: 'Menú degustación',
				startTime: '20:00',
				endTime: '23:00',
				days: ['thursday', 'friday', 'saturday'],
				price: 35.0,
				firstCoursesToShare: true,
				secondCoursesToShare: false,
				dessertsToShare: true,
				includesBread: true,
				drinks: { water: true, wine: true, softDrinks: false, beer: false },
				includesCoffeeAndDessert: 'both',
				minimumPeople: 2,
				hasMinimumPeople: true,
				dishes: [
					{
						id: 'user-dish-4',
						name: 'Tabla de embutidos ibéricos',
						description: 'Selección de jamón ibérico, chorizo y lomo',
						extraPrice: 5,
						category: DishCategory.APPETIZERS,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: false,
					},
					{
						id: 'user-dish-5',
						name: 'Lubina a la sal',
						description: 'Lubina fresca con costra de sal y hierbas',
						extraPrice: 0,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: false,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: true,
						isVegan: false,
					},
				],
			},
		],
		'user-rest-3': [
			{
				id: 'user-menu-3',
				name: 'Brunch weekend',
				startTime: '10:00',
				endTime: '14:00',
				days: ['saturday', 'sunday'],
				price: 8.5,
				firstCoursesToShare: false,
				secondCoursesToShare: false,
				dessertsToShare: false,
				includesBread: false,
				drinks: { water: false, wine: false, softDrinks: true, beer: false },
				includesCoffeeAndDessert: 'coffee',
				minimumPeople: 1,
				hasMinimumPeople: false,
				dishes: [
					{
						id: 'user-dish-6',
						name: 'Tostadas con aguacate',
						description: 'Pan tostado con aguacate, tomate y huevo',
						extraPrice: 0,
						category: DishCategory.MAIN_COURSES,
						isVegetarian: true,
						isLactoseFree: true,
						isSpicy: false,
						isGlutenFree: false,
						isVegan: false,
					},
				],
			},
		],
	};

	return menuMap[id] || [];
};

// Reseñas para los restaurantes del usuario
export const getUserRestaurantReviews = (restaurantId: string): Review[] => {
	const reviewsMap: Record<string, Review[]> = {
		'user-rest-1': [
			{
				id: 'user-review-1',
				userId: 'customer1',
				userName: 'Ana García',
				userAvatar: 'https://randomuser.me/api/portraits/women/1.jpg',
				rating: 4.5,
				comment:
					'Excelente comida casera y muy buen precio. El servicio es muy amable.',
				date: '2024-06-10',
				photos: [
					'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=300',
				],
				restaurantId: restaurantId,
				restaurantName: 'La Taberna del Abuelo',
				restaurantImage:
					'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
				restaurantResponse: {
					message:
						'¡Muchas gracias Ana! Nos alegra saber que disfrutaste de la experiencia.',
					date: '2024-06-11',
				},
			},
			{
				id: 'user-review-2',
				userId: 'customer2',
				userName: 'Miguel Rodriguez',
				userAvatar: 'https://randomuser.me/api/portraits/men/2.jpg',
				rating: 4.0,
				comment: 'Buena paella y ambiente familiar. Repetiremos seguro.',
				date: '2024-06-05',
				photos: [],
				restaurantId: restaurantId,
				restaurantName: 'La Taberna del Abuelo',
				restaurantImage:
					'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
			},
		],
		'user-rest-2': [
			{
				id: 'user-review-3',
				userId: 'customer3',
				userName: 'Carmen López',
				userAvatar: 'https://randomuser.me/api/portraits/women/3.jpg',
				rating: 5.0,
				comment:
					'Una experiencia gastronómica increíble. Cada plato es una obra de arte.',
				date: '2024-06-08',
				photos: [
					'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=300',
					'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=300',
				],
				restaurantId: restaurantId,
				restaurantName: 'Bistro Mediterráneo',
				restaurantImage:
					'https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg',
				restaurantResponse: {
					message:
						'Carmen, muchísimas gracias por tu reseña. Es un placer tenerte como cliente.',
					date: '2024-06-09',
				},
			},
		],
		'user-rest-3': [
			{
				id: 'user-review-4',
				userId: 'customer4',
				userName: 'José Martinez',
				userAvatar: 'https://randomuser.me/api/portraits/men/4.jpg',
				rating: 3.5,
				comment:
					'Buen café pero el servicio es un poco lento. El ambiente es agradable.',
				date: '2024-06-01',
				photos: [],
				restaurantId: restaurantId,
				restaurantName: 'Café Central',
				restaurantImage:
					'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg',
			},
		],
	};

	return reviewsMap[restaurantId] || [];
};
